### ISSUE TITLE
Move bs-react-test-renderer off the reasonml-community org

### ISSUE THREAD

**Issue by ryyppy** [reasonml-community/bs-react-test-renderer#23]
Hey @wyze!

Since BuckleScript + Reason rebranded to ReScript, the `reasonml-community` org serves a different purpose now, so we'd like to figure out how to proceed with all the `bs-*` related projects in here.

Since you are the main contributor to this project, would it be possible to move this repo over to your own personal github handle? That way we can slowly clean up all the active / obsolete projects that are still in this org.

More context on the discussion here: https://forum.rescript-lang.org/t/github-organization-reasonml-community-rescript-community/1630

Would be great if you'd take ownership of this project :-)

Thanks

**Comment by ryyppy** [comment]
Ah and maybe it would be worth reconsidering the naming of the bindings as well, since the BuckleScript naming is almost completely gone.

Our binding package convention switched from the informal `bs-react-test-renderer` to `rescript-react-test-renderer` (basically prefixing everything with `rescript-`).

**Comment by wyze** [comment]
Done, thanks! I'll try and make some time to rename as well.

**Comment by ryyppy** [comment]
awesome, thanks for that!
